jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Restore Cache
      uses: actions/cache@v4.0.2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Build with Gradle
      run: './gradlew :app:assembleDebug

        '
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Etar_apk
        path: app/build/outputs/apk/debug/app-debug.apk
name: Android CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___android.yml
